package com.eternal_search.snakesim

interface SnakeMap {
	val cellCountX: Int
	val cellCountY: Int
	val foods: List<Food>
	val snakes: List<Snake>
	val walls: List<Point>
	val allowIdle: Boolean
	val noWalls: Boolean
	
	fun generateFood()
	
	fun eatFood(x: Int, y: Int): Food?
	
	data class Food(
			val x: Int,
			val y: Int,
			val autoGenerated: Boolean
	)
}
